// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig, env } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: "ts-node prisma/seed/seed.ts"
  },
  datasource: {
    // This is where Prisma 7 expects the URL now
    url: env('DATABASE_URL'),
    shadowDatabaseUrl: env("SHADOW_DATABASE_URL"),
  },
});

